# Generated by Django 5.2.7 on 2025-10-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('contraseña_usuario', models.CharField(max_length=20)),
                ('fecha_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('contraseña', models.CharField(default='contradefault', max_length=20)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='pagina.quizin')),
            ],
        ),
        migrations.AddField(
            model_name='quizin',
            name='id_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losquiz', to='pagina.usuario'),
        ),
    ]
