# Generated by Django 5.2.7 on 2025-10-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_perfil', models.CharField(max_length=50)),
                ('puntaje_min', models.IntegerField()),
                ('puntaje_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_puntaje', models.IntegerField()),
                ('puntaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_resultados', to='pagina.perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='pagina.quizin')),
            ],
        ),
        migrations.AddField(
            model_name='quizin',
            name='id_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='pagina.usuario'),
        ),
    ]
