# Generated by Django 5.2.7 on 2025-10-20 13:00

from django.db import migrations

def crear_perfiles_iniciales(apps, schema_editor):
    Perfiles = apps.get_model('pagina', 'Perfiles')
    
    # Perfiles iniciales
    # TODO: Poner la relacion con el Quizin

    Perfiles.objects.create(
        tipo_perfil='Conservador',
        puntaje_min=0,
        puntaje_max=33
    )
    
    Perfiles.objects.create(
        tipo_perfil='Neutro',
        puntaje_min=34,
        puntaje_max=66
    )
    
    Perfiles.objects.create(
        tipo_perfil='Gastador',
        puntaje_min=67,
        puntaje_max=100
    )

def eliminar_perfiles_iniciales(apps, schema_editor):
    Perfiles = apps.get_model('pagina', 'Perfiles')
    Perfiles.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_perfiles_iniciales, eliminar_perfiles_iniciales),
    ]
