# Generated by Django 5.2.7 on 2025-10-28 18:16

from django.db import migrations


def usuarios_test_3(apps, schema_editor):
    Usuario = apps.get_model('pagina', 'Usuario')
    Usuario.objects.create(**{'nombre': 'conservador', 'contraseña': '1234567890', 'perfil': None})
    Usuario.objects.create(**{'nombre': 'normal', 'contraseña': '1234567890', 'perfil': None})
    Usuario.objects.create(**{'nombre': 'arriesgado', 'contraseña': '1234567890', 'perfil': None})




class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(usuarios_test_3),
    ]
