# Generated by Django 5.2.7 on 2025-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_usuarios_test_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizin',
            name='tipo_perfil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
