# Generated by Django 5.2.7 on 2025-10-28 18:32

from django.db import migrations

def perfiles_asociados(apps, schema_editor):
    Quizin = apps.get_model('pagina', 'Quizin')
    Usuario = apps.get_model('pagina', 'Usuario')
    # Primero creamos los registros de Quizin referenciando usuarios existentes
    # Usamos el campo *_id para asignar por pk y evitar consultas innecesarias.
    q1 = Quizin.objects.create(**{'id_us_id': 1, 'puntaje': 0, 'tipo_perfil': 'Conservador'})
    q2 = Quizin.objects.create(**{'id_us_id': 2, 'puntaje': 55, 'tipo_perfil': 'Neutro'})
    q3 = Quizin.objects.create(**{'id_us_id': 3, 'puntaje': 100, 'tipo_perfil': 'Gastador'})

    # Ahora actualizamos el campo perfil de los usuarios para apuntar a los quizzes creados
    Usuario.objects.filter(id=1).update(perfil_id=q1.id)
    Usuario.objects.filter(id=2).update(perfil_id=q2.id)
    Usuario.objects.filter(id=3).update(perfil_id=q3.id)


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_quizin_tipo_perfil'),
    ]

    operations = [
        migrations.RunPython(perfiles_asociados)
    ]
