# Generated by Django 5.2.7 on 2025-10-28 18:45

from django.db import migrations

def test_funcion_puntaje(apps, schema_editor):
    Quizin = apps.get_model('pagina', 'Quizin')
    q1 = Quizin.objects.create(**{'puntaje': 10})

class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_perfiles_asociados'),
    ]

    operations = [
        migrations.RunPython(test_funcion_puntaje)
    ]
