# Generated by Django 5.2.7 on 2025-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_test_funcion_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
