# Generated by Django 5.2.7 on 2025-11-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_usuario_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
