# Generated by Django 5.2.7 on 2025-10-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='respuesta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta_2',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta_3',
            field=models.IntegerField(default=10),
        ),
    ]
