# Generated by Django 5.2.7 on 2025-11-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_preguntas_respuesta_1_preguntas_respuesta_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.CharField(max_length=500),
        ),
    ]
